version: '3.8'
services:
  web:
    build: .
    command: >
      sh -c "python onlinecourse/manage.py migrate &&
      python onlinecourse/manage.py loaddata onlinecourse/fixtures/data.json &&
      python onlinecourse/manage.py collectstatic --noinput &&
      python onlinecourse/manage.py runserver 0.0.0.0:8000 --insecure"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    environment:
      POSTGRES_DB: course
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -h db" ]
      interval: 5s
      timeout: 30s
      retries: 5

volumes:
  postgres_data:
  media_volume:
